apiVersion: v1
kind: Service
metadata:
  name: thruster-ui
spec:
  type: ClusterIP
  selector:
    app: thruster-ui
  ports:
    - protocol: TCP
      name: dev
      port: 3000
      targetPort: 3000
