# FROM node:15.12.0 AS build-step
# WORKDIR /app
# COPY entrypoint.sh /entrypoint.sh
# RUN chmod +x /entrypoint.sh
# ADD . .
# RUN npm install
# RUN npm rebuild esbuild
# RUN exec "$@"
# RUN npm run build
# RUN npm run optimize

FROM nginx:1.18-alpine
COPY nginx.conf /etc/nginx/nginx.conf
# COPY --from=build-step /app/dist /frontend/dist
COPY /dist /frontend/dist
