version: '3.8'

services:
  dev:
    build: 
      context: ./
      dockerfile: ../Dockerfile
    ports:
      - '3000:3000'
    # build: 
    #   context: ./
    #   dockerfile: ../Dockerfile.prod
    # ports:
    #   - '3000:80'
